version: "3.9"
services:
  frontend:
    image: ghcr.io/usharik/shopping-list/frontend:latest
    ports:
      - 8080:80
    depends_on:
      - backend

  backend:
    image: ghcr.io/usharik/shopping-list/backend:latest
    ports:
      - 8080
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://db:3306/shopping_list_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    depends_on:
      - db
    command: bash -c "/apps/wait-for-mysql.sh db && /apps/entrypoint.sh"
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
    - my-db:/var/lib/mysql

volumes:
  my-db:

networks:
  net:

